services:
  postgres_db:
    image: postgres:15-alpine
    container_name: enterprise_reconciliation_db
    environment:
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_DB=${POSTGRES_DB}"
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  minio_s3:
    image: minio/minio
    container_name: enterprise_s3_storage
    environment:
      - "MINIO_ROOT_USER=${MINIO_ROOT_USER}"
      - "MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}"
    ports:
      - "9090:9000"
      - "9091:9001"
    command: server /data --address ":9000" --console-address ":9001"
    volumes:
      - s3data:/data
    restart: unless-stopped

  ollama_llm:
    image: ollama/ollama
    container_name: enterprise_ai_auditor
    ports:
      - "11434:11434"
    volumes:
      - ollamadata:/root/.ollama
    restart: unless-stopped

  airflow:
    image: apache/airflow:2.9.0
    container_name: enterprise_airflow
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - .:/opt/airflow/project
    environment:
      - "AIRFLOW__CORE__LOAD_EXAMPLES=False"
      - "_PIP_ADDITIONAL_REQUIREMENTS=requests==2.32.3 --extra-index-url https://elsai-core-package.optisolbusiness.com/root/elsai-prompts/ elsai-prompts==1.1.0 minio psycopg2-binary"

      # Passed securely from .env
      - "ELSAI_API_KEY=${ELSAI_API_KEY}"
      - "ELSAI_PROJECT_ID=${ELSAI_PROJECT_ID}"
      - "AIRFLOW_CONN_FINANCIAL_DB=${AIRFLOW_CONN_FINANCIAL_DB}"

      - "MINIO_ROOT_USER=${MINIO_ROOT_USER}"
      - "MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}"

      # Passed securely from .env
      - "FALLBACK_AI_PROMPT=${FALLBACK_AI_PROMPT}"

      # Database Environment Variables
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_DB=${POSTGRES_DB}"

      # Forces Airflow to create the fixed admin user on startup
      - "_AIRFLOW_WWW_USER_CREATE=true"
      - "_AIRFLOW_WWW_USER_USERNAME=${AIRFLOW_ADMIN_USER}"
      - "_AIRFLOW_WWW_USER_PASSWORD=${AIRFLOW_ADMIN_PASSWORD}"
      - "_AIRFLOW_WWW_USER_ROLE=Admin"
    command: standalone
    depends_on:
      - postgres_db
      - minio_s3
      - ollama_llm

volumes:
  pgdata:
  s3data:
  ollamadata:
